services:
  backend:
    restart: always
    container_name: backend
    command : bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py loaddata data.json &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/api/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres-network

  frontend:
    restart: always
    command : npm run dev -- --port 3000
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - postgres-network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres-network
volumes:
  postgres_data:

networks: 
  postgres-network:
    driver: bridge

