# Generated by Django 4.2.2 on 2023-06-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('nature', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tb_transaction_type',
            },
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('product', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='affiliates_system.transactiontype')),
            ],
            options={
                'db_table': 'tb_transaction_data',
            },
        ),
    ]
