# Generated by Django 4.2.2 on 2023-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondata',
            name='data',
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
