# Generated by Django 4.2.2 on 2023-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates_system', '0003_alter_transactiondata_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='seller',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
